### ISSUE TITLE
The link of binaries are down

### ISSUE THREAD

**Issue by johnparra** [davidgfnet/whatsapp-purple#200]
When I like download binarie for windows It not allow.
https://davidgf.net/nightly/whatsapp-purple/

**Comment by axel21a** [comment]
I agree that we too must learn to compilarci alone the dll, but since we do not have all the same knowledge and preparation, it would be useful for someone to tell us how to do, especially with windows.
knowledge is disclosed inthis way, do you regard to be a teacher with her students.
I personally think your great job, but I do not have your skills, then I tell you right now thanks for what you will do.
