### ISSUE TITLE
Error at Windows 7

### ISSUE THREAD

**Issue by adi88nugroho** [davidgfnet/whatsapp-purple#288]
I'm using latest Pidgin version and https://www.gosell.it/product/whatsapp-for-pidgin-20 on Windows 7 . The software always closed when I try to log in using WhatsApp account. I'm already follow the instruction.

Can you help me or I can get refund?

**Comment by bartnl** [comment]
Same on windows 8.1. After update 0.8.3 pidgin crashes at start. Windows application log logs the crash, but no additional info was given. How can I help?

**Comment by TexKiller** [comment]
I tried to contact the developer through the gosell.it page to report this, but I couldn't.

It seems that the crash only happens when there are messages to be received upon login. In my case those messages where from a group, but I don't know if it also happens when the messages are from individual contacts.

**Comment by davidgfnet** [comment]
Indeed, but that is fixed in version 0.8.4. Go check please.

**Comment by adi88nugroho** [comment]
Already fixed in latest version

**Comment by TexKiller** [comment]
Oops, sorry, I guess I downloaded version 0.8.3 just before 0.8.4 came out.

I have testes it and it is fixed :)
Thanks!
