### ISSUE TITLE
finding password

### ISSUE THREAD

**Issue by danielb2** [davidgfnet/whatsapp-purple#343]
I can't seem to figure out how to get my password. Is this still possible? If so, what method was used?

I tried: https://davidgf.net/whatsapp/pwd.html

however, I don't know what nickname to put and I get an error `Seems there was an error! Check your phone number again`

**Comment by danielb2** [comment]
I also tried this one: http://www.watools.es/pwd.html

**Comment by moyamo** [comment]
Seems there was an error! Check your phone number again

For the phone number, did you add your country code? If your phone number is 01342423 and you country code is 32 then you should enter 321342423.

    I don't know what nickname to put

The nick name is just your real name (or whatever you want your whatsapp contacts to see).

    It also caused me to have to verify the phone again. 

If you register a new password,  the official whatsapp client won't work, because the official client is using an outdated password.

**Comment by danielb2** [comment]
HI @moyamo 

I tried with country code like you've written. My area code is 408, and I put 1408xxx

I figured out the real name I'd used after whatsapp had me reauth because I had to verify

I ended up getting locked out of whatsapp for 24 hours so I gave up trying after that

**Comment by davidgfnet** [comment]
Hey. I think this has been answered many times before, either here, on other issues and other repos. See WART for more help on how to get the password. You can even extract it from your cellphone.

**Comment by danielb2** [comment]
I've tried everything I have found. WART seems to require Windows which I don't have. But perhaps the best bet then is to find a windows computer?

**Comment by davidgfnet** [comment]
@danielb2 Usw yowsup, multiplatform

**Comment by danielb2** [comment]
Thanks for your help, but how do I use that to get my password? I managed to install the yowsup-cli but I see no indication of being able to get password from there
