### ISSUE TITLE
axolotl: receiving empty messages in groups from some users

### ISSUE THREAD

**Issue by giordano** [davidgfnet/whatsapp-purple#350]
In a group, I receive empty messages from some users, but not all.  From the same users, I receive messages in private chats.

**Comment by giordano** [comment]
Follow up: some messages of mine to the same user in a private chat aren't delivered at all.  I have yet to discover the conditions under which this happens.  Stay tuned for more information!

**Comment by davidgfnet** [comment]
Interesting. You are on Linux right? compile it with debug:
make cleanall
make debug
And launch pidgin from a terminal, you should get a massive log with the transactions over the new. That might help.

**Comment by giordano** [comment]
Ok, I'll do it later.  Before reading your suggestion I received two messages from another user in another group: one was empty, the other one not.  It seems to be pretty random `:-/`

In the case reported in my first message of this thread, one message was just an emoticon, the other one text only.  Content of the message doesn't seem to be relevant.

**Comment by davidgfnet** [comment]
@giordano I experienced it myself: the first message from a contact is always empty. Haven't experimented with groups, I'm talking about 1:1 messages. Does that fit your experience?

**Comment by giordano** [comment]
No, I had only one private chat and I received all message (this was a buddy from which I previously received an empty message in a group), but some of my messages weren't delivered.

**Comment by neerajvashistha** [comment]
Its confusing, in one group it is able to deliver all the messages including emoticon(except the first) but in other it does not even receive the message.

**Comment by marga-debian** [comment]
I'm also getting lots of empty messages since my upgrade to HEAD yesterday.

**Comment by marga-debian** [comment]
I built the debug version and I have tons of output, it's hard to know what's useful. For the groups I'm in, I'm only seeing this from the group owner, although that might be coincidence. This is the most suspicious blob from the corresponding second:

Received message stanza...
Axolotl exception (parseGroupWhisperMessage): InvalidKeyIdException No key state 1570576394 in record!
Tag: receipt
at[id]=0031C436919A9893842
at[participant]=@s.whatsapp.net
at[t]=1453925554
at[to]=-1420631910@g.us
at[type]=retry
Data: ...
Tag: registration
Data: (\0/+\/+-\/)* ...
Tag: retry
at[count]=1
at[id]=0031C436919A9893842
at[t]=1453925553
at[v]=1
Data: ...

And then this:
(21:12:34) whatsapp: Received message 0031C436919A9893842 type: 0 (from )
Tree read:

Tag: message
at[from]=-1420631910@g.us
at[id]=0031C436919A9893842
at[notify]=
at[participant]=@s.whatsapp.net
at[t]=1453925554
at[type]=text
Data: ...
Tag: enc
at[count]=1
at[type]=pkmsg
at[v]=2
Data: 3\010\0/\/.+\0.\007\022!\005? ...

And also this:
(21:12:34) whatsapp: Received message 0031C436919A9893842 type: 0 (from )
Tree read:

Tag: chatstate
at[from]=-1420631910@g.us
at[participant]=@s.whatsapp.net
Data: ...
Tag: composing
Data: ...

**Comment by marga-debian** [comment]
This capture is probably more relevant.  phonenumber1 sent an image at (21:30:27). I received an empty message from phonenumber2 at (21:31:27). 

(21:31:26) blist: Updating buddy status for <phonenumber1> (WhatsApp)
Tree read:

Tag: message
at[from]=<phonenumber2>-1407098002@g.us
at[id]=4B82AA9F3BCF81457D1
at[notify]=<Name>
at[participant]=<phonenumber2>@s.whatsapp.net
at[t]=1453926687
at[type]=text
Data:  ...
 Tag: enc
 at[count]=1
 at[type]=pkmsg
 at[v]=2
 Data: 3\010\/+,\/.,\0*.\007\022!\005\/-, ...

Received message stanza...
Received message type 0 from <phonenumber2>-1407098002 at 1453926687
Tag: receipt
at[id]=4B82AA9F3BCF81457D1
at[t]=1
at[to]=<phonenumber2>-1407098002@g.us
at[type]=read
Data:  ...

(21:31:27) whatsapp: Got chat message from <phonenumber2>-1407098002: 
(21:31:27) whatsapp: Opening conversation window for <phonenumber2>-1407098002
Tree read:

Tag: ack
at[class]=receipt
at[from]=<phonenumber2>-1407098002@g.us
at[id]=4B82AA9F3BCF81457D1
at[type]=read
Data:  ...

(21:31:27) whatsapp: Received message 4B82AA9F3BCF81457D1 type: 0 (from )
Tree read:

Tag: presence
at[from]=<phonenumber3>@s.whatsapp.net
at[last]=1453926688
at[type]=unavailable
Data:  ...

**Comment by Raaff** [comment]
I can confirm this problem (I had one empty message today in a group chat, after a ~20 successful messages in private & group chats). This was with a build I made yesterday (before that I was using an old non-axolotl build). After reading about this issue, I did a `git pull && make clean && sudo make install` to get those logs, but pidgin crashed a second after showing the buddy list. (also with a normal `make` and with older versions of whatsapp-purple).

`(19:56:26) blist: Updating buddy status for xxxxxxxxxxx (WhatsApp)`
`terminate called after throwing an instance of 'int'`
`dns[29416]: Oops, father has gone, wait for me, wait...!`
`/usr/bin/pidgin: regel(*line*) 10: 29360 Afgebroken `(*=aborted*)` (geheugendump gemaakt) `(*=memorydump made*)` /usr/bin/pidgin.orig $*`

Turned out to be something with by blist.xml, when i deleted it it worked fine. When I put the old blist.xml back, and deleting the last halve (this was just a guess) of the whatsapp <contact> entries (of ~100) it worked . After putting back those contacts one by one (in blist.xml, not with the GUI), I found out some were making pidgin crash. It is working now with most of my contact list, but I have six contacts that I can't add to my blist.

BTW: @davidgfnet many thanks for implementing axolotl!

**Comment by davidgfnet** [comment]
Hey marga, would you mind to send me full traces + explanation on what happens in the UI over email please?
Hey Raaff, do a fresh clone please (or at least use make cleanall). In any case, send me an email with more details, if you could get a backtrace that'd be awesome!

**Comment by marga-debian** [comment]
I'll try to gather another trace plus a screenshot tomorrow, it's hard because it doesn't always happen.

Anyway, the one I pasted in my second message is pretty much full, only with the phone numbers redacted. In the message window, it just looks like:

(21:31:27) Person:

In some cases repeated over and over and in some other cases just once.

Anyway, I'll send you an email when I have a trace.

**Comment by davidgfnet** [comment]
Hey guys! Go ahead and test with this patch! :D

**Comment by marga-debian** [comment]
I've installed the new version and I'm testing it now. Before installing it, I noticed that the empty messages were actually messages from someone else, that I was not receiving at all.

It seems to be working now.  I'll report here if I see it happen again.

**Comment by marga-debian** [comment]
It's still happening.  Additionally, I'm receiving the conversations in a very weird order (when connecting after being disconnected). First comes everything from one person then everything from the other person, but in reality they should be intermingled.

**Comment by giordano** [comment]
With plugin updated to https://github.com/davidgfnet/whatsapp-purple/commit/a802c9ad61d797131f1456a16c0cad18781fd176 I just receive an empty message in a group. This wasn't the first message from that buddy since I installed support fro axolotl, I received messages with the right content since then, but for sure the rate of empty messages now is decreasing.
