### ISSUE TITLE
Ubuntu 16.04 / Packages  404  Not Found

### ISSUE THREAD

**Issue by delovoy** [davidgfnet/whatsapp-purple#386]
sudo apt-get update

```
W: Failed to fetch http://ppa.launchpad.net/whatsapp-purple/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/whatsapp-purple/ppa/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
```

Release date is known ?

**Comment by delovoy** [comment]
Temporarily solved the problem of the package assembly, But an older version installed protobuf-2.6.1 
the latest version of the package to collect refused. And also I had to install
libpurple-dev  libfreeimage-dev

Nevertheless , the release waiting after the stable version ubuntu16.04?

**Comment by davidgfnet** [comment]
Yeah I don't really update launchpad packages often. And its a pain in the ass to generate a package for every single damn ubuntu release...

**Comment by pedroskakum** [comment]
Is anyone able to use this package and connect in api whatsapp to use on clients like pidgin, for example?

**Comment by davidgfnet** [comment]
@pedroskakum No clients out there. Main reason is that Facebook sends lawyers to prosecute those who work on this. Sorry.

**Comment by pedroskakum** [comment]
@davidgfnet I understand, I'm from Brazil, I'm using a translator to translate our conversation, I'd just like to use whatsApp in pidgin, that's why this plugin was created right? If it is not about that, what are the reasons for trying to download the ppa. What I want to say is that I often see a topic and someone talking about it, more if nothing is working, what is the reason for so many discussions on the subject? Facebook blocks alternative connections to your advertising and publicity power project, I hate it, and I'm an open source lover, I just do not settle for having no way of doing that. Please if you want to talk to me: 'pedro.skakum@automasim.com.br'

**Comment by delovoy** [comment]
I just stopped using 'whatsapp' on the computer. It is more comfortable. No headache or so
